### ISSUE TITLE
Search/List page 

### ISSUE THREAD

**Issue by wuwentang** [yanis333/SOEN341_Website#106]
[sp = 10]

- [x] Filter options for the search results [sp = 6]
See more details in #90 

- [x] Additional search feature using tags (checkbox) [sp = 4]
See more details in #93

**Comment by TangMichael** [comment]
![searchtest](https://user-images.githubusercontent.com/25641760/37233612-e46d2960-23c1-11e8-9be1-883390bdae03.png)

This is the command line for the test

![commandlinetest1](https://user-images.githubusercontent.com/25641760/37233627-eceeb84c-23c1-11e8-9b92-ce5dc43d31ea.png)
