### ISSUE TITLE
Question page

### ISSUE THREAD

**Issue by wuwentang** [yanis333/SOEN341_Website#107]
[sp = 12]

- [x] Related questions feature for the user [sp = 4]
See more details in #92 

- [x] Add date for replies [sp = 2]
See more details in #102 

- [x] Choose best reply and make it at the top [sp = 6]
See more details in #91

**Comment by TangMichael** [comment]
Acceptance test

![questiontest](https://user-images.githubusercontent.com/25641760/37233586-c6b1653a-23c1-11e8-89e8-4354f20402c1.png)


This is the command line for the test

![commandlinetest2](https://user-images.githubusercontent.com/25641760/37233611-d877cfd4-23c1-11e8-91fe-244289cd3b40.png)
