### ISSUE TITLE
Achievement - Ideas

### ISSUE THREAD

**Issue by TangMichael** [yanis333/SOEN341_Website#150]
Ideas for achievement for issue #141

**Comment by wuwentang** [comment]
Currently have three main ideas for achievement: 

1. achievement based on number of questions posted; 
2. number of replies;
3. and number of replies based on certain tags.

**Comment by TangMichael** [comment]
To do those, you probably have to change the database accordingly. Take notes of those changes so I can update the database script.

**Comment by TangMichael** [comment]
Currently have 3 different type of achievements: number of question posted, number of upvotes and number of replies based on tags for sprint 4.
