### ISSUE TITLE
Login/Register Button

### ISSUE THREAD

**Issue by yanis333** [yanis333/SOEN341_Website#21]
[SP]=4

 
in the Top right of the Nav Bar -> 2 buttons
1) for Login
2) for Register

when click to Login a pop-up appear in the center of the page.
   1) you can look for some example here:
                     https://www.w3schools.com/bootstrap/bootstrap_modal.asp
          I will download the Bootstrap library but make sur you understand the code
 
   2) inside this popup needs to ask for those elements:
       username :
       password : 
  3) add a footer to the pop-up and add 2 buttons (if its not already here):
      a login button (to finaly login after entering the info ) and a close button(if the user changes his mind)

 for the Register same thing but the info are : 
   username:
   email addresse : 
   password : 
   password again:

**Comment by TangMichael** [comment]
Closed this issue and gonna merge it to #25 and #24
