### ISSUE TITLE
Add Question button

### ISSUE THREAD

**Issue by yanis333** [yanis333/SOEN341_Website#22]
[SP]=3

Create the Add Question button inside the Main page - > index.php

 You can put it where you want and name it as you wish.

its only the HTML and the CSS  for the Button  no JAVASCRIPT

ALSO

in the second page (add.php)  create the field to create a new question NOT A POP-UP

ask for:
 the Title of their question
the description
the programming language

and after that add a (Save question) button (ONLY HTML, CSS)

**Comment by TangMichael** [comment]
Added a basic button to connect to the add page.
