### ISSUE TITLE
#108 Create a forget password

### ISSUE THREAD

**Issue by yanis333** [yanis333/SOEN341_Website#23]
[sp] = 4

This is one of the feature for issue #108 .

Create a "forget password" below the Register button,  if the user forget his password , click on the ("forget password")
 
This is what it should happen step by step:

1) little pop-up to ask for their email to recover their password
     (a file named "recover_password.php" should have been created to recover a password)
2) after the user write his email, send the email to the recover_password.php to look if this email exist in the database in the table user.

3) if YES , send to his email his username and password according to his email

4) if NO , an ALERT should pop-up to say that their is no username according to this email

**Comment by phistanx** [comment]
We can add a security question and the user answers it or
we send an email and they click on it to then change their password
or we send an email with a password already made

**Comment by TangMichael** [comment]
Changing this to sprint 3.

**Comment by TangMichael** [comment]
updated it for sprint 4 new issue
