### ISSUE TITLE
#53 Login User

### ISSUE THREAD

**Issue by yanis333** [yanis333/SOEN341_Website#24]
[sp] = 2
Low risk, high value

This is one of the feature for issue #53.

This is how the Login button should behave step by step : 

1) After the user enter his username and password, 
     (a php file called Login.php should have been created in advance )
    send to the Login.php the Username and Password and look in the database if there is a match

2) if Yes, return to the front-end "True", which will mean to make the visibility of the button LOGIN, REGISTER and FORGET PASSWORD  to False and make his username visibility to true.

3) if No return to the front-end "False" which will mean to ALERT the user that "there is no match for this username and password try again please" <-- this sentence was an example

**Comment by TangMichael** [comment]
For 3, instead of saying wrong username and password. 

- Check if username match, if no username match, display "username does not exist"
- If username match but password do not, display "your password does not match"

This gives more information to the user.
