### ISSUE TITLE
#53 Register User

### ISSUE THREAD

**Issue by yanis333** [yanis333/SOEN341_Website#25]
[sp] = 2
Low risk, high value

This issue is one of the feature of issue #53.

This is how it should work : 

1) After the user enter his information, 
    verify if PASSWORD and WRITE AGAIN THE PASSWORD match -> use Javascript

2)  If it is ok ,(a php file called register.php should have been created in advance)
     send username and password to this php file and look in the database if this username already exist
 
2.1) if username exists, return False, ALERT the user that this username already exist

2.2) Otherwise, save it in the database his username and password and return True, make visibility FALSE to LOGIN,REGISTER and FORGET PASSWORD and make visibility True to username

**Comment by phistanx** [comment]
last part of 2.2) can be used to make the welcome username issue. We have to work together to have the same logic with issue #24 (login part).

**Comment by TangMichael** [comment]
welcome username done with the login issue #24
