### ISSUE TITLE
#53 Forgot password

### ISSUE THREAD

**Issue by yanis333** [yanis333/SOEN341_Website#35]
[sp] = 2
This is one of the feature for issue #53 .

1. Hyperlink "forgot password?" that the user can click if he forgets his password
2. Clicking on it will ask for his email.
3. It should compare to the database if any email matches with the one inputted.

   Not sure how to ask for password change as of now.

**Comment by TangMichael** [comment]
Updated the wrong issue for issue #53 - create forget password. Please refer to #23 for the right information.

This issue is to change the password in the setting page for a later sprint if this feature is going to be made.

**Comment by TangMichael** [comment]
Gonna put this for sprint 3.

**Comment by TangMichael** [comment]
closed this issue since it's the same as #23
