### ISSUE TITLE
Build Questions page

### ISSUE THREAD

**Issue by wuwentang** [yanis333/SOEN341_Website#56]
[sp] = 6

- [x] Nav bar : pinned on top of the page to display username of account currently "signed in"

- [x] Title block : displays question, description (of question), username, date

- [x] Reply block : displays replies to the question above

- [x] Upvote & DownVote : add the functionality & the permission to Accepte or Remove Reply

More details provided in other issues

**Comment by TangMichael** [comment]
Are there multiple navbar/header for each page? Issue #55 also have a navbar/header and the homepage #53 too?

**Comment by wuwentang** [comment]
For now we'll keep the navbar/header separate, but in the future we'll include one header file for every page!
